#+title: 怀念我的祖母
#+date:<2023-08-03 Thu>

我的祖母今天下午四点, 也就是英国时间上午九点, 在医院安详地离世了, 享耆寿九十一.
下午两点多, 我获悉此事, 开始动手写这篇文章.
祖母是在三周多之前入院的, 十分突然.
在这之前, 身体一直尚算硬朗, 只要天气好, 每天都出去散步, 如果爸妈不在家, 还自己做饭.

其实, 我自从 2018 年来到爱丁堡读博, 因为疫情和毕业的关系, 四年多一直没有能够回家看看老人家, 只有每隔两三周的电话聊天.
直到今年 4 月, 我才有机会回家看望祖母.
回到家的当晚, 祖母正好在卫生间, 我在客厅等着.
祖母走回客厅的时候, 不出所料, 她老了许多, 人显得更矮小了, 走路也慢了很多, 柱着拐杖, 但精神仍然矍铄.
她握了握我的手, 然后她坐在藤椅上, 我坐在木长椅上, 像十多年前我还在念中学的时候一样, 开始聊天.
往后在家的快三周里, 和十多年前一样, 只要我在家吃晚饭, 我们都会在饭后聊聊天.
聊的大都还是我的见闻, 只是从中学的事, 变成在北大的事, 再变成在英国的事.
偶尔祖母也会聊到她过去的事情, 尤其以前在海南岛种田的日子, 这些故事, 这么多年来, 从没有变.

我从小就和祖父母生活在一起.
那时侯父母都要上班, 在家里我基本上由祖父母照顾 ----- 祖父教我认字, 祖母给我做吃的.
祖父在我念小学三年级的时候去世了, 祖母则是一直照顾我直到高中毕业, 这么多年来, 无一句怨言.
其实要照顾我的饮食并不容易, 我在念中学的时候是走读, 每天回家吃午饭, 吃完又要回学校上学, 稍有点差驰就会有些匆忙.
有时她上街买菜, 或者是跟哪个熟悉的人聊天晚了, 我回到家饭还没好, 她就会很自责自己"煮不及吃".
祖母这么多年来的菜谱基本上没有变, 十分寡淡健康, 但是我小时候比较挑食, 她也会想办法, 比如试着做我喜欢吃的煎猪扒.
现在我当然知道这应该不算是真正的猪扒, 但是当时那个腌制过的爽滑的肉块的味道, 我却还记得.
上了大学, 离开了祖母, 每年寒暑假我回家, 招待我的必然是老火的莲藕猪蹄汤.
其实当时的我, 对这道汤是有点厌烦的, 但是为了不让老人家伤心, 每次还是照样喝 ----- 现在想起来, 当时只道是寻常.

祖母一辈子没有什么物质追求, 对我们孙辈, 只希望我们好好读书, 今后找一个好的工作.
她最大的遗憾, 就是没有机会念书, 只能上了几年夜校, 最后"担锄头"几十年.
我们三个堂姐弟, 最后都上了好的大学, 念到研究生, 也算是间接地圆了她的心愿, 对此她十分的自豪.
在退休的三十多年间, 靠着省吃俭用, 竟然攒下了二十万的积蓄 ----- 要知道, 她领的是农民的养老金.
今年回家的时候, 她给了我一个鼓鼓的红包, 说要给我买机票用, 还问我钱够不够花.
回到房里, 我打开红包, 里面竟然是两万块钱.

在祖母的词典里, 似乎永远只有付出和照顾, 没有被照顾.
这些年来, 哪怕她老了, 饭后收拾碗筷, 她还是和我爸妈争着来.
疫情的时候, 家乡的公交突然停摆了, 她刚好在城南在表姑那里聊天, 她就一个人柱着拐杖, 宁可自己走一个多小时回家, 也不愿找晚辈帮忙.
哪怕是入院前一天, 她应该已经相当不适, 还是想要自己去医院看病.

这么多年来, 祖母一直给我做好吃的, 我却没有好好给祖母做过一顿饭.
以前小的时候不懂事, 宁可打游戏也不乐意陪祖母去买菜, 给祖母打下手, 现在想来真是遗憾.
在海外留学, 不得不自己动手, 回家也总算给家里做了一顿饭, 做了个烧茄子和丝瓜鱿鱼.
这两道菜其实对于祖母来说是味道比较重了, 要是换作我爸做的, 估计就生气了.
祖母牙齿不好, 茄子没有问题, 但丝瓜她吃不了, 她还是耐着性子吮了几块, 高兴地连连说好吃.
我心里自然很高兴, 但是多年来的亲恩, 又岂是一顿饭能报尽, 一篇文章能说尽的!

今年五月份离开家的时候, 我心里一紧, 不知道什么时候再回来, 就在阳台和祖母合照了一张, 背后是祖母养了几十年的盆栽, 枝繁叶茂, 郁郁葱葱.
祖母走到门口, 再次握了握我的手, 祝我一路顺风, 没想到这一别也就成了永别.
现在我身在远方, 但我知道祖母必然将会永远关心着我 ----- 在祖母入院都那一天夜里, 我梦见祖母还在担心我有没有电视机看.
在梦里, 在二十年前楼下的电器一条街, 我和我的祖母一起进了一家店里, 从琳琅满目的彩电里, 挑了一台满意的彩电.
