#+title: 摩洛哥的中餐馆, Riad和里面的人
#+date:<2023-09-09 Sat>

今天听说摩洛哥发生了大地震, 震中在马拉喀什附近, 死亡上千.
我在 18 年 12 月曾经在摩洛哥旅游, 其中往返都途经马拉喀什, 今天翻开当年写的文字, 回忆起当时当地的萍水相逢的人们, 希望他们一切安好.
以下是当时写下的与当地生活的人有关的其中两篇, 只是隐去了人物信息和把自然段分开.

* 沙漠中的中餐馆
这个标题，自是取自三毛《撒哈拉的故事》。当年三毛的“中餐馆”在西撒哈拉小镇阿雍可是独一无二，而在当今的摩洛哥，中餐馆虽并非到处都是，要找到却并不困难，在哪个城市用谷歌地图一搜，都能找到好几家。
摩洛哥的食物实在是单调，正餐除了 couscous 便是 tagine，要么就是 skewer（烤串）或者 omelette。早餐也是千篇一律，基本上就是薄煎饼、牛角包或者硬面包涂上果酱、蜂蜜、黄油之类。事实上我们在第二天就已经算吃遍了摩洛哥的美食，接下来的几天，不过是在把餐盘上的肉类变来变去而已。吃腻了摩洛哥当地美食，想以公道的价格大快朵颐，并避开黑暗料理，菜式丰富多样的中餐馆就显得格外重要了。

我们的头两顿中餐都是在菲斯吃的。当时在撒哈拉沙漠吃得其实也不算坏，只不过当时已经是旅行的第五天，外加一日驱车大家都风尘仆仆，就想着去中餐馆吃顿好的。菲斯的老城，是个出了名的大迷宫，即使是谷歌地图也帮不了忙-----一来 GPS 讯号不好，二来街道仅约一米宽，在地图中无此数据库。第一天来到已经天黑，我们急着找中餐馆，又人生地不熟，竟然被三个一开始“热情”带路的混混敲了 50 块钱。我们委顿在名为“天府之国”的川菜馆里无精打采，心中自有一丝不忿。从沙漠出来，我们五人又四人身体状态欠佳，不敢点川菜，只点了宫保鸡丁、番茄炒蛋、胡萝卜炒牛肉片和豆腐汤四道寻常中国菜。上来之后我们无不精神大振，竟然很快就把四道菜吃得一干二净，心情也好了不少，毕竟是用家乡菜来填饱肚子。唯一不好的地方，就是不能像在摩洛哥餐厅一样随意对菜品指指点点，因为老板娘能听懂中文啊。

菲斯老城一共有三家中餐。“天府之国”深藏于老城，“如家”和“中华”却靠近菲斯老城的出口“蓝门”。我们第二天仍不满足，又去了“如家”。“如家”比“天府之国”装修得精致，有两位掌厨，一位掌摩菜，一位掌中菜，侍应其实大概就是老板、儿子和一位当地人，比“天府”多了一人，服务起来更显从容。我们点了饺子、豆腐和番茄炒蛋等，虽然没有辣菜，却相当美味。“如家”就开在蓝门的市场旁边，客人下单之后后厨立刻买去做，老板了解当日市场的原料状况，若原料不好则不予推荐，因此点上来的菜品总是新鲜。
买单的时候还和老板唠嗑了几句，才得知他们之前一直辗转欧洲、阿联酋等地开中餐馆，去年才来到摩洛哥。谈到原因，乃是摩洛哥前年开放对华免签，他们预想来摩的中国旅客会越来越多，再加上在沿海的几个大城市还将有大批中国企业进驻，便料定这是一个有潜力的市场。另一个好处则是摩洛哥是个中餐馆的处女地，菲斯全城的中餐馆仅四家，不比法国等地，中餐馆竞争激烈，生意难做。我问老板是否有语言问题，他说他来到此地，一句法语都不会讲，只能一日学一句法语。我不禁暗暗佩服老板，厨艺既佳，又有胆识流寓海外，瞅准商机，竟在菲斯老城这种人心叵测之地开出一家食肆来，殊不容易。

过了一天，在舍夫沙万的蓝色老城，我们在另外一家中餐馆“天空之城”吃中饭，这名字与倒是与这座蓝色麦地那非常相称，招牌则是蓝纹瓷盘的造型。这里的菜也颇为不错，在此略过不提。值得一提的是，我们来到舍夫沙万，身上的迪拉姆早就花光了，此次来吃，可谓“身无分文”。倒是老板娘心地善良，除了做食肆生意，还愿意与我们换汇，汇率也不差，只与实时汇率差 0.08，我们于是免去了透支信用卡和境外取款之苦，毕竟不知道这中间有多少重手续费。

当日看完日落，我们在一家叫 Lala Mesouda 的餐厅吃晚饭，这餐厅食物不错，老板也很热情。饭后，我们尝试在网上订往拉巴特的火车票，但苦于不懂法语，非常不顺利，餐馆里的人都说没有在网上订过火车票。我们生怕订票不及时火车票会卖光，只好在夜里前去找老板娘帮忙，老板娘虽不懂法语，也没订过火车票，却二话不说就唤了店里一个懂英法双语的当地小哥来帮忙，并把手提电脑借出。我心想，这就完全是念及同胞之谊了。我和小哥试了多次，网页上都说有系统错误，小哥还打电话给朋友询问。朋友不接电话，小哥面带歉意地跟我说不好意思他朋友可能睡了。后来他朋友接通了电话，也无良策解决，只道是售票系统的问题，小哥只好无奈放弃，我实在非常感动，握住他的手不住地道谢，他也用中文回我“不客气”。小哥其实是在学中文的，这大概是他的第四门语言了吧。在网页缓慢刷新之际，他看的是没有字幕的中国综艺节目，我问他是否能看懂，他说他听不懂，但也能藉此学一些中文。
我们出店前向老板娘也连声道谢，老板娘只道不客气，手头上仍然在飞快地算着帐，彼时已经是夜晚十点半了，不知道他们次日又要几点起来准备午市？步出店门，我不禁想，在海外开中餐馆，是需要多大的胆识和勇气？萍水相逢之缘，手头忙碌之际，老板娘和本地小哥却仍倾力相助，又是何等的善良？

* Riad 和里面的人
我们来之前就听说摩洛哥的 riad 非常特别，评价也颇为正面，于是在马拉喀什、菲斯和舍夫沙万的麦地那 (老城) 都订下了 riad. 这些 riad 都是深居老城的老房子，总体面积不大，一层基本上就三四个小房间，共三四层，顶层除了有客房还有天台。
客房的装修非常传统，门是木门，客房内外的装修都是以彩色马赛克为主，内部陈设颇为简陋，基本上就是床、梳妆台、小桌子、小盥洗室，灯饰也是各种传统的形状，灯光昏黄。基本上，在这样简陋的客房里，除了睡觉之外，并无其它合适的事情可做。
客房之外，灯光仍旧昏暗，仍是马赛克风格的装潢。虽可如此概括，不同的 riad 倒是有不同的风格。在马拉喀什和舍夫沙万的 riad，规模较大，中间有天井，可以望见四角的天空。在马拉喀什的 riad，马赛克用的是白色，在早上马赛克可以映出天井中蓝天的蓝色，如此一来整个 riad 便似浸没在一片清冷的蓝色光辉中。而舍夫沙万的 riad 则自身是天蓝色风格，活泼可爱，并不清冷。

这里的 riad 通常是包早餐的，早餐则是在天台吃。起床出来之后，在天台找到负责早餐的中年妇女，她自会给我们做好早餐。早餐也是千篇一律，基本上就是薄煎饼、牛角包或者硬面包涂上果酱、蜂蜜、黄油之类，外加一两杯加了糖的薄荷绿茶、牛奶或是橙汁。不过在天台吃早餐还是颇有意境的。早上的天台是微冷的，可以在此望见老城的概貌，又可以感受初升的太阳带来的暖意，还可以欣赏周边的各种奇形怪状的仙人掌盆栽。这甚至是接触自然界的好机会——在马拉喀什的时候，我们的蜂蜜、果酱还招引来三四只黄蜂，好不容易才请人用烟把他们熏走。
天台最大的好处，莫过于观星。晚上坐在天台的椅子上，仰头望去，便是满头的星星。沙漠的云非常少，虽有老城的灯光干扰，又有上凸月照亮，仍然能找到天顶附近的许多冬季亮星。在马拉喀什的第二宿，我和两位朋友就在天台上坐着聊天，桌上点着烛灯，在满天繁星的笼罩之下，漫谈星座知识和宇宙归宿。

Riad 的人，大概通常是老板或者老板的朋友，也不同于酒店的雇员，非常友好热情。在马拉喀什，当时朋友 S 身体不舒服，我下楼去取热水给他，这时前台有两个人，其中一个人说要让我付钱。我心中一凛，想起前一天在德吉玛广场交的学费，不禁有点害怕，忙问多少钱。那人哈哈一笑，说要一百万美元，我一听便知道是玩笑，便立刻应承给他支票。
在菲斯，我们从中餐馆吃完饭回来的时候迷路了，路上的大人小孩纷纷七嘴八舌地说哪个方向已经 close，便要跟着带路。我们知道这是不怀好意，冷冷地回绝，可是接连尝试了几次都找不到正道。这时只好打电话给 riad 的小哥，让他来接。我们连自己都不清楚自己在哪里，小哥英文不好，但仍不挂断电话耐心听。万分无奈之际，我们只好让周遭的咖啡店的老板用法语跟他说了，他随即就到，我们历经艰险，当下非常感动。在舍夫沙万，老板听说我们第二天一早七点半就要走，而厨师要八点才上班，竟六点多起床给我们做早餐，他说这是他第一次给客人准备早餐。他显然不熟练，做得相当慢，我们最后来不及，只好带走他做的早餐在车上吃了，得以在往拉巴特的五小时车程中不用挨饿。

作为“现代人”，我早已习惯了酒店那种房间宽敞明亮、待客中规中矩的感觉，忽而住进这种 riad，虽则房间环境不如酒店，可是又别有一番风味。这大概就像是在路边摊与超市、大排档与饭店之间的差别吧。你硬要说哪个好，我还真不容易说得出来。
