#+title: 给家里装了一台树莓派400
#+date: <2023-05-09 Tue>

家里的老电脑不行了, 趁着这次回国, 给家里换上了 [[https://www.raspberrypi.com/products/raspberry-pi-400/][树莓派 400]] , 运行 Ubuntu MATE 22.04 系统.

树莓派 400 的好处是键盘和主机一体, 节省空间, 布线简单, 价格便宜 (683 元), 配置对于家里老人来说也够用.
Ubuntu MATE 配置要求低, 容易入门, 并且对树莓派电脑有官方支持.

安装配置完毕后, 系统运行快速不卡顿, 中文支持良好, 完美满足家人上网, 管理手机照片和视频通话的需求, 家里人很快就上手了.
兹记录安装配置过程如下.

* 硬件
卖家已经提供了一根网线和一个无线鼠标.

树莓派 400 只有 micro HDMI 接口, 没有 HDMI 接口和 3.5 mm 的音频接口.
而家里的显示器是 VGA 的, 音箱是 3.5 mm 口, 因此需要从 micro HDMI 转出一个视频口和一个音频口.
淘宝上似乎没有 micro HDMI 直接转 VGA 的线, 因此购买了一根 micro HDMI 转 HDMI 线, 外加一根 HDMI 转 VGA 带 3.5 mm 母口的线 (共 45 元).

存储卡用的是 Ubuntu MATE 官网推荐的 Kingston microSDXC Canvas Go Plus, 容量 128 GB (88 元).
[[https://ubuntu-mate.org/raspberry-pi/compatibility/][据官网所述]], 存储卡对性能影响较大, 须谨慎选择存储卡, 不要贪便宜.

* 系统安装
Ubuntu MATE 提供了预制的镜像, 只需下载 ARM64 版本的镜像([[https://ubuntu-mate.org/raspberry-pi/download/][页面]]), 按照[[https://ubuntu-mate.org/raspberry-pi/install/][官方教程]]把镜像烧录到存储卡, 然后插入到卡槽, 给树莓派连接上屏幕, 鼠标和电源, 按提示或官方教程安装即可.

* 换源, 安装中文支持和输入法
安装完毕的系统中文支持并不完善, 需下载并安装中文支持, 而默认的国外软件源十分缓慢.
因此首先换源, 可参见[[https://blog.csdn.net/Brendon_Tan/article/details/107107550][这篇博客]].
之后在 ~菜单~ 中进入 ~控制中心~, 选择 ~语言支持~, 会自动检查语言支持, 提示"语言支持没有安装完整", 此时安装语言支持.
安装完语言支持后, 在 ~语言支持~ 菜单中的 ~键盘输入法系统~ 选择 Fcitx 5 (也就是小企鹅输入法), 然后在 ~菜单~ 中找到 ~Fcitx 配置~, 把所需的输入法移动到当前输入法中, 此时从菜单中运行 Fcitx 5, 中文输入法应该可以使用了.

然而此时遇到一个 bug, 也就是在火狐或者 Chromium 浏览器中无法显示选字框, 但在其它软件中正常, 原因未明.
解决方案为重新安装 Fcitx 5:
1. 先在终端卸载 Fcitx 5:
    #+begin_src shell
sudo apt remove fcitx*
    #+end_src
2. 参考了[[https://zhuanlan.zhihu.com/p/508797663][这篇文章]], 运行以下命令:
    #+begin_src shell
sudo apt install fcitx5 \
fcitx5-chinese-addons \
fcitx5-frontend-gtk4 fcitx5-frontend-gtk3 fcitx5-frontend-gtk2 \
fcitx5-frontend-qt5
    #+end_src
3. 重新在 ~Fcitx 配置~ 中配置所需输入法.
4. 设置环境变量, 在 ~/etc/profile~ 文件中写入:
   #+begin_src shell
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
   #+end_src
5. 令 Fcitx 随系统启动时自启动. 在 ~控制中心~ 中找到 ~启动应用程序~, 点击 ~添加~, 名称为 ~fcitx5~, 命令为 ~/usr/bin/fcitx5~.

* 改变外观布局
Ubuntu MATE 的默认外观为 Gnome 2 的经典样式, 而家里人习惯使用类似于 Windows XP 的体验.
Ubuntu MATE 已经内置了相应的功能, 在 ~控制中心~ 中找到 ~MATE Tweak~, 选择 ~面板~, 把面板改为 ~Redmond~ 即可.
该面板的问题是似乎无法添加更多的快速启动按钮, 只能编辑现有的按钮,  并且如果试用了其它面板布局, 编辑过的快速启动按钮会丢失.

* 安装 ESR 版的火狐浏览器和 uBlock Origin
Ubuntu MATE 自带一个火狐浏览器, 但是并非 ESR 版本, 意味着未经签名的插件, 比如广告屏蔽的 [[https://github.com/gorhill/uBlock][uBlock Origin]] 将无法安装 (火狐在中国不提供 uBlock Origin).
而 ESR 版本的火狐并不在 Ubuntu 的软件源中, 因此在 ~Boutique 商店~ 中使用第三方源安装 Firefox ESR (在国内速度比较缓慢), 并从终端卸载自带的火狐:
#+begin_src shell
sudo snap remove firefox
#+end_src
然后:
1. 从[[https://github.com/gorhill/uBlock/releases][uBlock Origin 的 Releases页面]]中下载后缀为 ~.xpi~ 的火狐插件文件.
2. 在火狐中打开 ~about:config~ 页面, 搜索 ~xpinstall.signatures.required~, 把值设置为 ~false~.
3. 在 ~扩展与主题~ 菜单中点击齿轮按钮, 选择 ~从文件安装附加组件...~, 选择之前下载的 ~.xpi~ 文件即可安装.

其它有用的插件, 比如 [[https://addons.mozilla.org/zh-CN/firefox/addon/darkreader/][Dark Reader]], 可以直接从火狐官网安装.

* 其它有用的软件
+ 腾讯会议 (Linux 版的 QQ 暂不支持视频通话), 直接从官网下载 ARM64 版本的 ~deb~ 包安装即可. 家里的罗技 USB 摄像头可以即插即用. 视频效果良好不卡顿.
+ [[https://github.com/qier222/YesPlayMusic][YesPlayMusic]], 优秀的网易云音乐第三方客户端.
  直接在 Releases 页面中下载 ARM64 版本的 ~tar.gz~ 文件, 解压缩, 运行 ~yesplaymusic~ 文件即可. 国内 GitHub 下载速度缓慢, 可使用 [[https://ghproxy.net/][ghproxy]] 加速下载.
+ 星际译王, 类似于金山词霸的词典软件. 在终端输入 ~sudo apt install stardict~ 安装.
  星际译王自身不带有词典, 可从作者的[[http://download.huzheng.org/][网站]]下载词典, 个人较为喜欢的是[[http://download.huzheng.org/zh_CN/][此页面]]中的朗道英汉和朗道汉英词典.
  下载后, 运行:
  #+begin_src shell
tar xvf ~/下载/<某字典>.tar.bz2
cd ~/下载/<某字典>
sudo cp * /usr/share/stardict/dic/stardict-dict
  #+end_src
  重启星际译王即可.

* 未实现的功能
+ 使用 VNC 通过公网 IP 实现远程控制, 远程帮助家里解决软件问题.
